# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

jobs:
  - job: 'main_branch_build'
    displayName: 'Build'
    # Set timeout for jobs
    timeoutInMinutes: 60
    strategy:
      matrix:
        'java-11':
          jdk_version: '11'
        'java-17':
          jdk_version: '17'
    # Base system
    pool:
      vmImage: 'Ubuntu-22.04'
    # Pipeline steps
    steps:
      - task: Cache@2
        inputs:
          key: 'maven-cache | $(System.JobName) | **/pom.xml'
          restoreKeys: |
              maven-cache | $(System.JobName)
              maven-cache
          path: $(HOME)/.m2/repository
        displayName: Maven cache
      - template: 'templates/steps/setup_docker.yaml'
      - template: 'templates/steps/setup_java.yaml'
        parameters:
          JDK_VERSION: $(jdk_version)

      - bash: mvn clean verify
        env:
          # Test container optimization
          TESTCONTAINERS_RYUK_DISABLED: TRUE
          TESTCONTAINERS_CHECKS_DISABLE: TRUE
        displayName: "Strimzi test container build & verify"

      - bash: ".azure/scripts/push_to_nexus.sh"
        env:
          GPG_PASSPHRASE: $(GPG_PASSPHRASE)
          GPG_SIGNING_KEY: $(GPG_SIGNING_KEY)
          NEXUS_USERNAME: $(NEXUS_USERNAME)
          NEXUS_PASSWORD: $(NEXUS_PASSWORD)
        displayName: "Push artifacts to Nexus repository"
        condition: and(succeeded(), or(eq(variables['build.sourceBranch'], 'refs/heads/main'), startsWith(variables['build.sourceBranch'], 'refs/tags/')))

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: "Integration tests"
        condition: always()